CREATE TABLE public.books (
  id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  author varchar(80),
  launch_date timestamp NOT NULL,
  price numeric(32,2) NOT NULL,
  title varchar(100),
  registrationdate timestamp not null,
  CONSTRAINT books_pkey PRIMARY KEY (id)
) ;

COMMENT ON COLUMN books.id IS 'Identificador único dos registros';
COMMENT ON COLUMN books.author IS 'Autor do livro';
COMMENT ON COLUMN books.launch_date IS 'Data da edição do livro';
COMMENT ON COLUMN books.price IS 'Preço de venda do livro';
COMMENT ON COLUMN books.title IS 'Título do livro';
CREATE INDEX idx_books_title ON books (title);
COMMENT ON COLUMN person.registrationdate IS 'Data de cadastro do registro na base de dados';
--ENGINE=InnoDB DEFAULT CHARSET=latin1;